import esbuild from 'esbuild';
import { copyFileSync, existsSync, mkdirSync, readFileSync, readdirSync, rmSync } from 'fs';
import { builtinModules } from 'module';
import path from 'path';
import process from 'process';

if (existsSync('.env.local')) {
  const envContent = readFileSync('.env.local', 'utf-8');
  for (const line of envContent.split('\n')) {
    const match = line.match(/^([^#=]+)=["']?(.+?)["']?$/);
    if (match && !process.env[match[1]]) {
      process.env[match[1]] = match[2];
    }
  }
}

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/`;

const prod = process.argv[2] === 'production';
const watch = process.argv[2] === '--watch';
const pluginId = 'sidecard';
const deployFiles = new Set(['main.js', 'manifest.json', 'styles.css']);
const obsidianVault = process.env.OBSIDIAN_VAULT;
const obsidianPluginPath = obsidianVault && existsSync(obsidianVault)
  ? path.join(obsidianVault, '.obsidian', 'plugins', pluginId)
  : null;

function pruneStalePluginFiles(pluginPath) {
  const keep = new Set([...deployFiles, 'data.json']);
  for (const name of readdirSync(pluginPath)) {
    if (keep.has(name)) continue;
    rmSync(path.join(pluginPath, name), { recursive: true, force: true });
    console.log(`Removed stale Obsidian plugin artifact: ${name}`);
  }
}

const copyToObsidian = {
  name: 'copy-to-obsidian',
  setup(build) {
    build.onEnd((result) => {
      if (result.errors.length > 0 || !obsidianPluginPath) return;

      if (!existsSync(obsidianPluginPath)) {
        mkdirSync(obsidianPluginPath, { recursive: true });
      }

      pruneStalePluginFiles(obsidianPluginPath);

      for (const file of deployFiles) {
        if (!existsSync(file)) continue;
        copyFileSync(file, path.join(obsidianPluginPath, file));
        console.log(`Copied ${file} to Obsidian plugin folder`);
      }
    });
  },
};

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ['src/main.ts'],
  bundle: true,
  plugins: [copyToObsidian],
  external: ['obsidian', 'electron', '@codemirror/autocomplete', '@codemirror/collab', '@codemirror/commands', '@codemirror/language', '@codemirror/lint', '@codemirror/search', '@codemirror/state', '@codemirror/view', '@lezer/common', '@lezer/highlight', '@lezer/lr', ...builtinModules],
  format: 'cjs',
  target: 'es2018',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: 'main.js',
  minify: prod,
});

if (watch) {
  await context.watch();
} else {
  await context.rebuild();
  await context.dispose();
}
